### ISSUE TITLE
feat: conditionally disable lighting

### ISSUE THREAD

**Issue by CarsonBurke** [Lommix/bevy_solis_2d#5]
It would be nice to conditionally disable all lighting and coinciding performance costs of the plugin. For example, when the camera is significantly zoomed out such that cascades look significantly inaccurate and the performance cost needs to be voided

**Comment by CarsonBurke** [comment]
Sorry if there is already a way to do this, but I'm not aware of one

**Comment by Lommix** [comment]
There is currently no way other than removing the SDF shape. I will add a `DisableEmitter` Tag component.

**Comment by Lommix** [comment]
There are now 2 new tag-components:

`DisableEmitter` for any Emitter-Entity and `DisableLight` for any radiance camera. `DisableLight` will completely shut off the radiance pipeline and any associated performance cost.
